# Generated by Django 5.0.3 on 2024-09-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plane',
            options={'ordering': ['plane_brand', 'plane_model']},
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='passengers',
        ),
    ]
