# Generated by Django 5.0.3 on 2024-09-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_plane_options_alter_passenger_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Regisetered Flight Passenger'},
        ),
        migrations.AlterModelOptions(
            name='planeseat',
            options={'verbose_name': 'Seat on the Flight', 'verbose_name_plural': 'Seats on the Flight'},
        ),
    ]
